In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [7]:
from sklearn.ensemble import RandomForestRegressor

In [8]:
from sklearn.model_selection import GridSearchCV
#from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error','absolute_error'],
'max_features': ['sqrt','log2'],
'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(indep, dep)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [9]:
# print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'squared_error', 'max_features': 'sqrt', 'n_estimators': 100}:

In [10]:
table=pd.DataFrame.from_dict(re)

In [11]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.312013,0.012006,0.035430,0.002208,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.834649,0.756879,0.825889,0.821283,0.833216,0.814383,0.029162,8
1,2.894483,0.078490,0.134918,0.022358,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.859448,0.780122,0.858479,0.828417,0.842565,0.833806,0.029169,1
2,0.311649,0.013998,0.031108,0.004921,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.833787,0.777517,0.842233,0.813529,0.813058,0.816025,0.022362,6
3,2.826945,0.075974,0.127771,0.022844,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.854294,0.777064,0.858880,0.827673,0.839889,0.831560,0.029385,4
4,1.036163,0.039987,0.027764,0.003865,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.843233,0.740105,0.847793,0.819902,0.825620,0.815331,0.039034,7
5,10.103580,0.100050,0.132138,0.010511,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.858626,0.777502,0.855264,0.828743,0.848807,0.833788,0.029991,2
6,1.057013,0.042500,0.030492,0.003777,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.832091,0.774104,0.831940,0.816511,0.834468,0.817823,0.022773,5
7,9.803614,0.811454,0.115144,0.025229,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.856083,0.780416,0.851082,0.831493,0.847117,0.833238,0.027663,3

In [12]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 29
BMI: 34
Children: 1
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 0

In [13]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])#change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[4643.9172875]

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(