In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset= pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
indep= dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset[['charges']]

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid={'criterion':['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],'max_features': ['auto','sqrt','log2'],'n_estimators':[10,100]}
grid=GridSearchCV(RandomForestRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Users\PAVAN\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\PAVAN\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PAVAN\anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\PAVAN\anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\PAVAN\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\PAVAN\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PAVAN\anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\PAVAN\anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\PAVAN\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\PAVAN\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.79235428 0.81225427 0.79095894 0.81191835
        nan        nan 0.78984355 0.81269522 0.78696076 0.81351559
        nan        nan 0.78916782 0.81401165 0.79243722 0.81147329
        nan        nan 0.80611485 0.80982528 0.79436402 0.81229956]
  warnings.warn(
C:\Users\PAVAN\anaconda3\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [10]:
re=grid.cv_results_
print("The R_score value for best parameter {}".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'n_estimators': 100}

In [11]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004055,0.001259,0.000000,0.000000,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.003826,0.001414,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.057426,0.012338,0.008150,0.002018,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.860976,0.779847,0.793726,0.797595,0.729628,0.792354,0.042022,12
3,0.377284,0.007770,0.028202,0.003155,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.862510,0.791068,0.812411,0.826436,0.768846,0.812254,0.031812,5
4,0.051293,0.006069,0.006842,0.000978,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.834574,0.771699,0.795086,0.795983,0.757453,0.790959,0.026223,13
5,0.407438,0.016571,0.026643,0.003531,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.865783,0.787216,0.809119,0.824102,0.773371,0.811918,0.032105,6
6,0.001933,0.000710,0.000000,0.000000,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.001439,0.000116,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.104450,0.011491,0.005977,0.000941,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.822909,0.791686,0.791975,0.794801,0.747847,0.789844,0.024040,14
9,0.945796,0.024144,0.026209,0.003778,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.866773,0.799513,0.805165,0.820387,0.771637,0.812695,0.031304,3
10,0.093821,0.003229,0.005884,0.001308,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.823577,0.767143,0.774297,0.804991,0.764795,0.786961,0.023282,16
11,0.973098,0.044861,0.028882,0.003548,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.861133,0.793984,0.810658,0.830086,0.771716,0.813516,0.030590,2
12,0.002352,0.000674,0.000000,0.000000,friedman_mse,auto,10,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.001867,0.000484,0.000000,0.000000,friedman_mse,auto,100,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.046970,0.001557,0.006243,0.000647,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.853443,0.769928,0.773972,0.791129,0.757367,0.789168,0.033904,15
15,0.378305,0.009727,0.025232,0.002491,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.868676,0.791845,0.810860,0.826257,0.772421,0.814012,0.032769,1
16,0.045470,0.003685,0.005149,0.000407,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.844449,0.789906,0.791213,0.804083,0.732535,0.792437,0.035880,11
17,0.379016,0.020166,0.024954,0.007219,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.862238,0.793070,0.801867,0.833246,0.766945,0.811473,0.033060,7
18,0.001201,0.000135,0.000000,0.000000,poisson,auto,10,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.001198,0.000173,0.000000,0.000000,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.052422,0.004204,0.006373,0.000433,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.870840,0.786652,0.797249,0.807633,0.768200,0.806115,0.034890,9
21,0.403444,0.042910,0.026177,0.005513,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.865308,0.787388,0.799008,0.831977,0.765445,0.809825,0.035097,8
22,0.047584,0.004404,0.005351,0.000102,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.843956,0.769224,0.786947,0.807605,0.764088,0.794364,0.029115,10
23,0.409029,0.010242,0.021222,0.002080,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.861381,0.788874,0.806920,0.834601,0.769722,0.812300,0.032548,4

In [12]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=float(input("Sex Male 0 or 1:"))
smoker_yes_input=float(input("Smoker yes 0 or 1:"))

Age: 30
BMI: 40
Children: 3
Sex Male 0 or 1: 1
Smoker yes 0 or 1: 1

In [13]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print('Future_Prediction={}'.format(Future_Prediction))

Future_Prediction=[47084.6565298]