In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset= pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
indep= dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset[['charges']]

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid={'kernel':['rbf','poly','sigmoid','linear'],'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}
grid=GridSearchCV(SVR(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\Users\PAVAN\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [9]:
re=grid.cv_results_
print("The R_score value for best parameter {}".format(grid.best_params_))

The R_score value for best parameter {'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}

In [10]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.059378,0.003032,0.023169,0.001818,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.004055,0.013366,-0.103821,-0.095119,-0.101604,-0.056625,0.053504,35
1,0.045325,0.002784,0.010837,0.001387,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.056274,0.069532,-0.045601,-0.025079,-0.049592,0.001107,0.051309,32
2,0.057911,0.006206,0.012818,0.000978,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.049905,0.075905,-0.046585,-0.041004,-0.046507,-0.001657,0.053391,34
3,0.044919,0.003275,0.009289,0.001338,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.377969,0.479601,0.317872,0.337979,0.324422,0.367569,0.059777,25
4,0.056059,0.003785,0.025558,0.003582,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.004126,0.013244,-0.103775,-0.095165,-0.101602,-0.056634,0.053486,36
5,0.050794,0.006807,0.010584,0.001060,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.054964,0.071297,-0.046513,-0.024157,-0.049652,0.001188,0.051594,31
6,0.074076,0.007169,0.015908,0.001599,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.049644,0.076323,-0.046798,-0.040824,-0.046521,-0.001635,0.053474,33
7,0.064325,0.006446,0.011021,0.001475,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.377969,0.479601,0.317872,0.337979,0.324422,0.367569,0.059777,25
8,0.065135,0.002891,0.025772,0.002054,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.300573,0.339474,0.173708,0.217991,0.183375,0.243024,0.065733,29
9,0.050717,0.001928,0.009904,0.000739,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.540643,0.575051,0.474839,0.535730,0.424640,0.510181,0.053582,21
10,0.066437,0.005943,0.012824,0.001229,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.478364,0.561673,0.428331,0.450454,0.431701,0.470105,0.049110,24
11,0.060122,0.003534,0.009846,0.000904,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.584474,0.655818,0.553380,0.576939,0.546881,0.583498,0.038787,19
12,0.065259,0.001564,0.025794,0.001606,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.301041,0.338741,0.174086,0.217641,0.183403,0.242982,0.065542,30
13,0.056504,0.005831,0.010568,0.000890,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.537117,0.579373,0.471840,0.537966,0.424478,0.510155,0.054955,22
14,0.067421,0.004678,0.013503,0.001964,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.478930,0.563200,0.427152,0.451250,0.432199,0.470546,0.049762,23
15,0.063620,0.004238,0.009789,0.000925,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.584474,0.655818,0.553380,0.576939,0.546881,0.583498,0.038787,19
16,0.078052,0.003980,0.028299,0.003340,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.733044,0.746232,0.686773,0.717920,0.649158,0.706625,0.034902,12
17,0.074042,0.011171,0.010737,0.000763,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.829631,0.802622,0.799620,0.800321,0.735580,0.793555,0.031072,7
18,0.073470,0.007033,0.014358,0.001627,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.296082,0.372281,0.216401,0.291265,0.351325,0.305471,0.054387,28
19,0.074509,0.010719,0.010113,0.000642,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.605304,0.588725,0.623230,0.537931,0.616726,0.594383,0.030560,17
20,0.075928,0.003218,0.029188,0.003864,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.733334,0.745892,0.687037,0.717769,0.649174,0.706641,0.034825,11
21,0.081775,0.013284,0.010605,0.001862,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.828213,0.802622,0.799348,0.800587,0.735555,0.793265,0.030757,8
22,0.068681,0.005196,0.013056,0.000746,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.400044,0.366097,0.242217,0.288461,0.351407,0.329645,0.056742,27
23,0.067120,0.002372,0.009369,0.000284,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.605304,0.588725,0.623230,0.537931,0.616726,0.594383,0.030560,17
24,0.079166,0.003034,0.026104,0.001744,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.814076,0.781092,0.794081,0.794075,0.733656,0.783396,0.027014,10
25,0.113758,0.022992,0.009940,0.000891,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.845403,0.805639,0.816733,0.805143,0.754961,0.805576,0.029233,4
26,0.070243,0.001611,0.013329,0.000870,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.401855,-0.508082,-0.452827,-0.751013,-0.111859,-0.445127,0.205197,38
27,0.082084,0.003579,0.010549,0.002156,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.605277,0.583646,0.697368,0.532547,0.681425,0.620053,0.061555,15
28,0.077659,0.004225,0.026208,0.001382,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.814295,0.780971,0.794227,0.793983,0.733663,0.783428,0.027068,9
29,0.115318,0.005015,0.010004,0.001180,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.845581,0.805624,0.816612,0.805133,0.754962,0.805582,0.029272,3
30,0.077797,0.003857,0.014104,0.001902,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.385658,-0.537098,-0.474912,-0.477335,-0.111187,-0.397238,0.150976,37
31,0.082872,0.009286,0.009164,0.000435,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.605277,0.583646,0.697368,0.532547,0.681425,0.620053,0.061555,15
32,0.083615,0.002747,0.025359,0.001500,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.828670,0.790265,0.811049,0.812892,0.741829,0.796941,0.030140,6
33,0.167991,0.083668,0.008548,0.001423,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.846775,0.805323,0.817309,0.805191,0.758994,0.806718,0.028279,2
34,0.069410,0.003133,0.012771,0.000418,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-1.090896,-1.761043,-1.734344,-2.304377,-1.050280,-1.588188,0.469215,39
35,0.091188,0.002713,0.009935,0.001197,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.657470,0.583501,0.697875,0.529117,0.655785,0.624750,0.060379,13
36,0.082419,0.004207,0.024952,0.001431,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.828795,0.790105,0.811123,0.812857,0.741835,0.796943,0.030174,5
37,0.193175,0.059233,0.007768,0.002466,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.846874,0.805331,0.817283,0.805239,0.758988,0.806743,0.028307,1
38,0.075742,0.004477,0.013418,0.001522,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-1.761871,-2.139307,-1.704369,-2.340839,-1.048739,-1.799025,0.443311,40
39,0.080479,0.007595,0.006954,0.001252,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.657470,0.583501,0.697875,0.529117,0.655785,0.624750,0.060379,13

In [11]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=float(input("Sex Male 0 or 1:"))
smoker_yes_input=float(input("Smoker yes 0 or 1:"))

Age: 30
BMI: 40
Children: 3
Sex Male 0 or 1: 1
Smoker yes 0 or 1: 1

In [12]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print('Future_Prediction={}'.format(Future_Prediction))

Future_Prediction=[1976933.80991145]